spring.application.name=lms
spring.datasource.url=jdbc:postgresql://ep-royal-glitter-ao3lxz2z-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Il94ZNyTzwOv
server.port=8081
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true